install.packages("ggplot2") # Workshop dependencies
install.packages("rmarkdown")
install.packages("dplyr")
install.packages("languageserver")
install.packages("tidyr")
install.packages("pacman")
install.packages("devtools")
install.packages("stringr")
install.packages("scales")
install.packages("minqa") # Package dependencies (should import with devtools::install_github())
install.packages("numDeriv")
install.packages("matrixStats")
install.packages("neotoma2")
devtools::install_github("https://github.com/QuinnAsena/multinomialTS")
